### PR TITLE
Add p5 callbacks and examples

### PR DESCRIPTION
**Pull request by nickmcintyre**
I added a few missing callback methods and examples.

Not sure if this will trip anyone up in practice when setting `Sk.canvas`, but the second argument to the `p5()` function is the sketch's [parent element](https://github.com/processing/p5.js/wiki/Global-and-instance-mode#specifying-parent-html-element), not a `<canvas>` element.

### CODE REVIEW

**Comment by s-cork** [comment]
good point - I was trying to avoid polluting the Sk namespace. See https://github.com/skulpt/skulpt/pull/1143

are you happy for me to push the changes in p5.js (adding the function names) and leave the examples as a separate pr that can be made in Skulpt.

as to when this gets merged in skulpt. Who knows - it can take a while for prs to get over the line - longer if they touch the core like this one does. But I hope it won't take too long.

**Comment by nickmcintyre** [comment]
Yep! Just removed the examples directory.

I plan to put your work into production next week in the [coding environment](https://editor.computiful.org/) I run for my classes; will keep you posted.

**Comment by s-cork** [comment]
can you also remove the changes to package/json and the doc/static in this pr

**Comment by s-cork** [comment]
@nickmcintyre  - i've raised an issue on p5 since I wanted to see if there was something I should have done differently here and whether there was potential to have this use case supported as part of the p5 api.

See discussion here: https://github.com/processing/p5.js/issues -> Integration Question - namespace other than window

I feel like i'm not explaining myself very well though - if you had any comments then do jump in...

**Pull request merged**
